[package]
name = "fixity-core"
version = "0.1.0"
authors = ["Bradlee Speice <bradlee@speice.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.nom]
version = "5.0"
features = []

[dependencies.num-traits]
version = "0.2"
features = []

[dependencies.typenum]
version = "1.11"
features = []
